import type { Review } from "./types"

export const reviews: Review[] = [
  { id: "1", author: "Marcus T.", location: "New York, USA", rating: 5, title: "The headphone I have been waiting for.", body: "I have been reviewing audio gear for eleven years. AURA One is the first consumer headphone that made me forget I was wearing a consumer headphone. The ANC is not just good -- it is genuinely eerie. The build quality feels like something from a much more expensive category.", date: "March 14, 2024", product: "AURA One", verified: true },
  { id: "2", author: "Priya S.", location: "London, UK", rating: 5, title: "Two years in and still perfect.", body: "The build quality is unlike anything at this price point. Two years in and they look better than the day I opened the box. The leather has developed a beautiful patina. Nothing has creaked, rattled, or failed.", date: "February 28, 2024", product: "AURA One", verified: true },
  { id: "3", author: "James K.", location: "Singapore", rating: 5, title: "The only travel essential I never leave without.", body: "I travelled 140 days last year. AURA One came every single time. The noise cancellation on long-haul flights is genuinely life-changing. Battery never let me down. Not once.", date: "January 15, 2024", product: "AURA One", verified: true },
  { id: "4", author: "Lena M.", location: "Berlin, Germany", rating: 5, title: "Audiophile approved.", body: "As someone who owns $3,000 planar headphones, I was sceptical. AURA Arc is not a reference-class headphone in the traditional sense but the soundstage is wider than anything I have heard at this price. The driver matching is exceptional.", date: "March 2, 2024", product: "AURA Arc", verified: true },
  { id: "5", author: "David R.", location: "Toronto, Canada", rating: 4, title: "Almost perfect earbuds.", body: "AURA Drift has the best spatial audio implementation I have tested. The fit is genuinely comfortable for 8-hour sessions. My only gripe is that the case could be slightly slimmer. Everything else is flawless.", date: "February 10, 2024", product: "AURA Drift", verified: true },
  { id: "6", author: "Amara N.", location: "Lagos, Nigeria", rating: 5, title: "Worth every penny.", body: "I was hesitant about the price but after three months I understand. These headphones make you want to listen to music you thought you already knew. The AURA One revealed details in albums I have heard hundreds of times.", date: "January 30, 2024", product: "AURA One", verified: true },
  { id: "7", author: "Tom H.", location: "Sydney, Australia", rating: 5, title: "Stem changed how I work.", body: "I run meetings all day. AURA Stem means I never miss a word from the room while still hearing my music. The bone conduction tech is far better than competitors I have tried. No fatigue after 10 hours.", date: "March 8, 2024", product: "AURA Stem", verified: true },
  { id: "8", author: "Sofia L.", location: "Madrid, Spain", rating: 4, title: "Reference quality in a small package.", body: "AURA Void with a balanced cable out of a good DAC/amp is genuinely special. The staging and imaging are class-leading. I took off one star only because the stock cable is a bit stiff. The sound itself is reference-class.", date: "February 19, 2024", product: "AURA Void", verified: true },
  { id: "9", author: "Noah P.", location: "Amsterdam, Netherlands", rating: 5, title: "My everyday headphone.", body: "AURA Form is what I reach for every single day. It sounds better than it has any right to at this price, it folds flat into my bag, and the ANC is good enough to make open offices bearable. Exactly what I needed.", date: "March 18, 2024", product: "AURA Form", verified: true },
  { id: "10", author: "Yuki T.", location: "Tokyo, Japan", rating: 5, title: "Exceptional in every way.", body: "The attention to detail in the AURA One is extraordinary. Every surface, every hinge, every stitched edge feels considered. And then you put them on and the sound matches the build. I have recommended these to everyone I know.", date: "January 22, 2024", product: "AURA One", verified: true },
]